#!/bin/bash

N=$1

#step=0
my_array=()
size_array=0

touch report.log

while true
do
	#step=$(( $step + 1 ))	
	my_array+=(1 2 3 4 5 6 7 8 9 10)
	size_array=$(( $size_array + 10 ))
	
	if [[ "$size_array" -ge "$N" ]];then
		echo $size_array >> report.log
		break
	fi
	
done
