#!/bin/bash

file_name=$1  #a.Передается один парамет

if [[ $# -ne 1 ]]
then
	echo "Sorry! Only one parameter is needed!"
	exit 1
fi

#b.Проверяет, создан ли скрытый каталог  в домашнем каталоге пользователя. Если он не создан---создает его

trash=~/.trash
if [[ ! -d $trash ]]
then
	mkdir $trash
fi

#c.Создает в этом каталоге жесткую ссылку на переданный файл с уникальным именем и удаляет файл в текущем каталоге
#ln file link

link_file=$(date +%s)
ln $file_name "$trash/$link_file"
rm $file_name

#d.В скрытый файл  в домашнем каталоге пользователя помещается запись, содержащая полный исходный путь к удаленному файлу и имя созданной жесткой ссылки

log=~/.trash.log
echo "$(pwd)/$file_name" >> $log
echo "$link_file" >> $log 









