#!/bin/bash
#Задайте запуск скрипта из пункта 1 в каждую пятую минут каждого часа в день недели,
#в который вы будете выполнять работу

#corntab file
# f1  f2  f3   f4 f5 program
#min hour day mon week

*/5 * * * * user/lab3/1_directory
